"""make profile fields nullable

Revision ID: 1ff29dd755ab
Revises: c7b68892dc8a
Create Date: 2025-11-13 12:40:21.332714

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ff29dd755ab"
down_revision: Union[str, Sequence[str], None] = "c7b68892dc8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profile", "birthdate", existing_type=sa.DATE(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profile", "birthdate", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
